# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Bodel
paginate:       5
baseurl:        "/"
url:            "https://jiaxigu.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Jiaxi Gu
  url:          github.com/jiaxigu
  email:        mcjxgu@163.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
